ESX = exports["es_extended"]:getSharedObject()

ADMINPANEL = {
    Key = "F5",
    AdminNames = true,
    AdminNamesColor = {r = 255, g = 0, b = 0},
    AdminNamesSize = 0.4,
    RefreshTime = 5, -- UM SO KLEINER UM SO SCHLECHTERE PERFORMANCE
    Permissions = {
        ['openMenu'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['setjobwave'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['frakaufloesen'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['frakannounce'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['bringfraktion'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['resetped'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['setgroup'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['giveteammoney'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['setped'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['spawnvehicle'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['givevehicle'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['reviveallwave'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['heal'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['revive'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['clearinventory'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['loadoutclear'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['giveweaponwave'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['giveitemwave'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['givemoneywave'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['charreset'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['support'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['skinchanger'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['bring'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['goto'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['freeze'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['revive'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ["hochjagen"] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
        },
        ["wegrammen"] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
        },
        ['flasche'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
        },
        ['flashbang'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
        },
        ["blackscreen"] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
        },
        ["announce"] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
        },
        ["teamchat"] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
        },
        ["setdimension"] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',


          },
    },
    Catogories = {
        ['Administration'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['Moderation'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['Development'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
            'mod',
            'support',
            'guide',
        },
        ['Fahrzeugfunktionen'] = {
            'projektleitung',
            'management',
            'teamleitung',
            'admin',
        },
        ['Fraktionsmanagement'] = {
            'admin',
            'projektleitung'
        },
        ['Teammanagement'] = {
            'admin',
            'projektleitung'
        },
        ['Trollfunktionen'] = {
            'admin',
            'projektleitung'
        },
        ['Clearmenü'] = {
            'admin',
            'projektleitung'
        },
        ['Rückerstattung'] = {
            'admin',
            'projektleitung'
        },
        ['Umgebung'] = {
            'admin',
            'projektleitung',
        },
        ['Ankündigungen'] = {
            'admin',
            'projektleitung'
        }
    },
    Aduties = {
        ["projektleitung"] = {
            ['tshirt_1'] = 15,
            ['tshirt_2'] = 0,
            ['torso_1'] = 287,
            ['torso_2'] = 2,
            ['decals_1'] = 0,
            ['decals_2'] = 0,
            ['arms'] = 9,
            ['pants_1'] = 114,
            ['pants_2'] = 2,
            ['shoes_1'] = 78,
            ['shoes_2'] = 2,
            ['helmet_1'] = -1,
            ['helmet_2'] = 0,
            ['mask_1'] = 135,
            ['mask_2'] = 2,
            ['chain_1'] = 0,
            ['chain_2'] = 0,
            ['ears_1'] = 0,
            ['ears_2'] = 0,
            ['bags_1'] = 0,
            ['bags_2'] = 0,
            ['hair_1'] = 0,
            ['hair_2'] = 0,
            ['bproof_1'] = 0,
            ['bproof_2'] = 0
        },
        ["management"] = {
            ['tshirt_1'] = 15,
            ['tshirt_2'] = 0,
            ['torso_1'] = 287,
            ['torso_2'] = 0,
            ['decals_1'] = 0,
            ['decals_2'] = 0,
            ['arms'] = 9,
            ['pants_1'] = 114,
            ['pants_2'] = 0,
            ['shoes_1'] = 78,
            ['shoes_2'] = 0,
            ['helmet_1'] = -1,
            ['helmet_2'] = 0,
            ['mask_1'] = 135,
            ['mask_2'] = 0,
            ['chain_1'] = 0,
            ['chain_2'] = 0,
            ['ears_1'] = 0,
            ['ears_2'] = 0,
            ['bags_1'] = 0,
            ['bags_2'] = 0,
            ['hair_1'] = 0,
            ['hair_2'] = 0,
            ['bproof_1'] = 0,
            ['bproof_2'] = 0
        },
        ["admin"] = {
            ['tshirt_1'] = 15,
            ['tshirt_2'] = 0,
            ['torso_1'] = 287,
            ['torso_2'] = 3,
            ['decals_1'] = 0,
            ['decals_2'] = 0,
            ['arms'] = 9,
            ['pants_1'] = 114,
            ['pants_2'] = 3,
            ['shoes_1'] = 78,
            ['shoes_2'] = 3,
            ['helmet_1'] = -1,
            ['helmet_2'] = 0,
            ['mask_1'] = 135,
            ['mask_2'] = 3,
            ['chain_1'] = 0,
            ['chain_2'] = 0,
            ['ears_1'] = 0,
            ['ears_2'] = 0,
            ['bags_1'] = 0,
            ['bags_2'] = 0,
            ['hair_1'] = 0,
            ['hair_2'] = 0,
            ['bproof_1'] = 0,
            ['bproof_2'] = 0
        },
        ["mod"] = {
            ['tshirt_1'] = 15,
            ['tshirt_2'] = 0,
            ['torso_1'] = 287,
            ['torso_2'] = 4,
            ['decals_1'] = 0,
            ['decals_2'] = 0,
            ['arms'] = 9,
            ['pants_1'] = 114,
            ['pants_2'] = 4,
            ['shoes_1'] = 78,
            ['shoes_2'] = 4,
            ['helmet_1'] = -1,
            ['helmet_2'] = 0,
            ['mask_1'] = 135,
            ['mask_2'] = 4,
            ['chain_1'] = 0,
            ['chain_2'] = 0,
            ['ears_1'] = 0,
            ['ears_2'] = 0,
            ['bags_1'] = 0,
            ['bags_2'] = 0,
            ['hair_1'] = 0,
            ['hair_2'] = 0,
            ['bproof_1'] = 0,
            ['bproof_2'] = 0
        },
        ["support"] = {
            ['tshirt_1'] = 15,
            ['tshirt_2'] = 0,
            ['torso_1'] = 287,
            ['torso_2'] = 5,
            ['decals_1'] = 0,
            ['decals_2'] = 0,
            ['arms'] = 9,
            ['pants_1'] = 114,
            ['pants_2'] = 5,
            ['shoes_1'] = 78,
            ['shoes_2'] = 5,
            ['helmet_1'] = -1,
            ['helmet_2'] = 0,
            ['mask_1'] = 135,
            ['mask_2'] = 5,
            ['chain_1'] = 0,
            ['chain_2'] = 0,
            ['ears_1'] = 0,
            ['ears_2'] = 0,
            ['bags_1'] = 0,
            ['bags_2'] = 0,
            ['hair_1'] = 0,
            ['hair_2'] = 0,
            ['bproof_1'] = 0,
            ['bproof_2'] = 0
        },
        ["teamleitung"] = {
            ['tshirt_1'] = 15,
            ['tshirt_2'] = 0,
            ['torso_1'] = 287,
            ['torso_2'] = 6,
            ['decals_1'] = 0,
            ['decals_2'] = 0,
            ['arms'] = 9,
            ['pants_1'] = 114,
            ['pants_2'] = 6,
            ['shoes_1'] = 78,
            ['shoes_2'] = 6,
            ['helmet_1'] = -1,
            ['helmet_2'] = 0,
            ['mask_1'] = 135,
            ['mask_2'] = 6,
            ['chain_1'] = 0,
            ['chain_2'] = 0,
            ['ears_1'] = 0,
            ['ears_2'] = 0,
            ['bags_1'] = 0,
            ['bags_2'] = 0,
            ['hair_1'] = 0,
            ['hair_2'] = 0,
            ['bproof_1'] = 0,
            ['bproof_2'] = 0
        },
        ["analyst"] = {
            ['tshirt_1'] = 15,
            ['tshirt_2'] = 0,
            ['torso_1'] = 510,
            ['torso_2'] = 3,
            ['decals_1'] = 0,
            ['decals_2'] = 0,
            ['arms'] = 3,
            ['pants_1'] = 227,
            ['pants_2'] = 3,
            ['shoes_1'] = 147,
            ['shoes_2'] = 3,
            ['helmet_1'] = -1,
            ['helmet_2'] = 0,
            ['mask_1'] = 245,
            ['mask_2'] = 3,
            ['chain_1'] = 0,
            ['chain_2'] = 0,
            ['ears_1'] = 0,
            ['ears_2'] = 0,
            ['bags_1'] = 0,
            ['bags_2'] = 0,
            ['hair_1'] = 0,
            ['hair_2'] = 0,
            ['bproof_1'] = 0,
            ['bproof_2'] = 0
        },
    }

}
